// Generated by https://quicktype.io

export interface UserType {
  _id: string;
  first_name: string;
  last_name: string;
  client_id: string;
  email: string;
  phone: string;
  status: Status;
  createdAt: string;
}

export interface Status {
  access: string;
}
